// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmDznocuHNsys2WiYz5JcQEy71Qy00ZWs',
    appId: '1:731557793809:web:8377a8bd1adc2bc1c621b0',
    messagingSenderId: '731557793809',
    projectId: 'firebase-todo-ui',
    authDomain: 'fir-todo-ui.firebaseapp.com',
    storageBucket: 'firebase-todo-ui.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxDAhUAb_L8R5QIULpriUvB8dqbmy-7W4',
    appId: '1:731557793809:android:c7fe6064e398ac0ec621b0',
    messagingSenderId: '731557793809',
    projectId: 'firebase-todo-ui',
    storageBucket: 'firebase-todo-ui.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDei5s8vBKCX6NS_UY1y9Gkp7_X1xcjCKU',
    appId: '1:731557793809:ios:623331d0ec901de1c621b0',
    messagingSenderId: '731557793809',
    projectId: 'firebase-todo-ui',
    storageBucket: 'firebase-todo-ui.appspot.com',
    iosBundleId: 'com.example.firebaseTodoUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDei5s8vBKCX6NS_UY1y9Gkp7_X1xcjCKU',
    appId: '1:731557793809:ios:4210419bcf54d941c621b0',
    messagingSenderId: '731557793809',
    projectId: 'firebase-todo-ui',
    storageBucket: 'firebase-todo-ui.appspot.com',
    iosBundleId: 'com.example.firebaseTodoUi.RunnerTests',
  );
}
